import{a as f,S as m,i as n}from"./assets/vendor--6n4cVRZ.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const d=f.create({baseURL:"https://pixabay.com/api/",params:{key:"54667939-2958d96aa870b71b0c19ccb5c",image_type:"photo",orientation:"horizontal",safesearch:!0}});async function g(s){return(await d.get("",{params:{q:s}})).data}const c=document.querySelector(".gallery"),l=document.querySelector(".loader"),y=new m(".gallery a",{captionDelay:250,captionsData:"alt"});function h(s){const r=s.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:a,comments:u,downloads:p})=>`<li class="gallery-item">
        <a href = "${i}" class="gallery-link">
        <img src = "${o}" alt = "${e}" class="gallery=image" /></a>
        <div class="info" >
        <p>Likes: ${t}</p>
        <p>Views: ${a}</p>
        <p>Comments: ${u}</p>
        <p>Downloads: ${p}</p>
        </div>
        </li>`).join("");c.insertAdjacentHTML("beforeend",r),y.refresh()}function b(){c.innerHTML=""}function L(){l.classList.add("is-visible")}function v(){l.classList.remove("is-visible")}const w=document.querySelector(".form");w.addEventListener("submit",s=>{s.preventDefault();const r=s.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search query!",position:"topRight"});return}b(),L(),g(r).then(o=>{if(!o.hits.length){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}h(o.hits)}).catch(o=>{n.error({message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}).finally(()=>v())});
//# sourceMappingURL=index.js.map
